# Generated by Django 5.2.17 on 2026-09-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('payment_reference', models.CharField(db_index=True, max_length=40)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PROCESSED', 'Processed'), ('IGNORED', 'Ignored'), ('FAILED', 'Failed')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'webhook_events',
                'ordering': ('-received_at',),
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_required',
            field=models.BooleanField(default=False),
        ),
    ]
