# Generated by Django 5.2.17 on 2026-09-26 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_at', models.DateTimeField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='centres.diagnosticcentre')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='centres.diagnostictest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='booking_user_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='booking_amount_positive'), models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING', 'CONFIRMED'))), fields=('user', 'centre', 'test', 'appointment_at'), name='booking_active_unique')],
            },
        ),
    ]
